---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cjjcoder.
--- DateTime: 2024/12/28 18:21
---
local voucherId = ARGV[1]

local userId= ARGV[2]

local orderId= ARGV[3]

--- 数据key
--- 库存key
local stockKey="seckill:stock" .. voucherId
---订单key
local orderKey="seckill:stock" .. voucherId

if (tonumber(redis.call('get',stockKey)) <= 0) then
    ---库存不足，返回1
    return 1
end
if (redis.call('sismember',order,userId) == 1) then
    return 2
end
---扣库存，然后下单
redis.call('incrBy',stockKey,-1)
---下单
redis.call('sadd',orderKey,userId)
---发送到消息队列中，xadd
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',userId,'id',orderId)

return 0